# fly.toml file generated for letsgrow on 2023-04-17T22:23:47+07:00

app = "letsgrow"
primary_region = "sin"

[env]
  PORT = "8080"
  NODE_ENV = "development"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
